# Generated by Django 5.2.5 on 2026-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.CharField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('phone_num', models.CharField(blank=True, default='', max_length=50)),
                ('in_charge_person', models.CharField(blank=True, choices=[('Alwin', 'Alwin'), ('Henry', 'Henry'), ('Vanessa', 'Vanessa'), ('Loh', 'Loh'), ('Other', 'Other')], default=None, max_length=100, null=True)),
                ('proposal_prepared_by', models.CharField(blank=True, choices=[('Haziq', 'Haziq'), ('Asyraf', 'Asyraf'), ('Faqihah', 'Faqihah'), ('Farah', 'Farah'), ('Loh', 'Loh'), ('Other', 'Other')], default=None, max_length=100, null=True)),
                ('engineers', models.CharField(blank=True, default='', max_length=500)),
                ('installer', models.CharField(blank=True, default='', max_length=200)),
                ('installed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customer_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer File',
                'verbose_name_plural': 'Customer Files',
                'db_table': 'CustomerFile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('defect_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('accident_date', models.DateField(blank=True, null=True)),
                ('resolution_deadline', models.DateField(blank=True, null=True)),
                ('defect_type', models.CharField(choices=[('Lighting Strike', 'Lighting Strike'), ('Fire Disaster', 'Fire Disaster'), ('Other', 'Other')], default='Other', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'db_table': 'Defect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('no_insurance', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_period', models.DateField()),
                ('end_period', models.DateField()),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('ins_co', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceRenewalNotice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('renewal_year', models.IntegerField()),
                ('due_date', models.DateField()),
                ('is_dismissed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'InsuranceRenewalNotice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('warranty_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Warranty',
                'managed': False,
            },
        ),
    ]
