# Generated by Django 5.2.5 on 2026-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRenewalNotice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('renewal_year', models.IntegerField()),
                ('due_date', models.DateField()),
                ('is_dismissed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'InsuranceRenewalNotice',
                'managed': False,
            },
        ),
    ]
